"""
Generate a PyInstaller Windows version-info resource file for npmpi.

Usage:
    python scripts/gen_version_info.py VERSION [OUTPUT_PATH]

VERSION is a dotted version string (e.g. "0.1.17", "v0.1.17", or
"0.0.0-dev") - padded/truncated to exactly 4 integer parts, since Windows
version resources are always major.minor.build.revision. Any non-numeric
trailing part (like "-dev") is dropped rather than erroring, so this also
works for the "0.0.0-dev" placeholder release.yml uses on non-tag runs.

Without this, PyInstaller leaves the exe's Windows file-version metadata
unset, and Explorer's Properties > Details tab / PowerShell's
`Get-Command`/`(Get-Command npmpi).Version` show a default 0.0.0.0
regardless of the actual npmpi release. Pass the generated file to
PyInstaller with --version-file.

Used by both build_exe.ps1 (local builds, version read from pyproject.toml)
and .github/workflows/release.yml (CI builds, version read from the git tag).
"""

from __future__ import annotations

import sys

TEMPLATE = """# UTF-8
#
# Auto-generated by scripts/gen_version_info.py - do not hand-edit.
# Consumed by PyInstaller's --version-file flag to stamp Windows file-
# version metadata onto the built npmpi.exe.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({tuple_str}),
    prodvers=({tuple_str}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'Travis Sylvester'),
        StringStruct(u'FileDescription', u'npmpi - unified NPM/Pi-hole CLI'),
        StringStruct(u'FileVersion', u'{dotted}'),
        StringStruct(u'InternalName', u'npmpi'),
        StringStruct(u'LegalCopyright', u'MIT License'),
        StringStruct(u'OriginalFilename', u'npmpi.exe'),
        StringStruct(u'ProductName', u'npmpi'),
        StringStruct(u'ProductVersion', u'{dotted}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


def parse_version(raw: str) -> tuple[int, int, int, int]:
    cleaned = raw.strip()
    if cleaned.lower().startswith("v"):
        cleaned = cleaned[1:]
    parts = [p for p in cleaned.split(".") if p != ""]
    nums = [int(p) if p.isdigit() else 0 for p in parts]
    nums = (nums + [0, 0, 0, 0])[:4]
    return (nums[0], nums[1], nums[2], nums[3])


def main() -> None:
    if len(sys.argv) < 2:
        print("usage: gen_version_info.py VERSION [OUTPUT_PATH]", file=sys.stderr)
        raise SystemExit(1)

    raw_version = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else "version_info.txt"

    parts = parse_version(raw_version)
    dotted = ".".join(str(p) for p in parts)
    tuple_str = ", ".join(str(p) for p in parts)

    text = TEMPLATE.format(tuple_str=tuple_str, dotted=dotted)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"Wrote {output_path} (version {dotted}, from input '{raw_version}')")


if __name__ == "__main__":
    main()
